language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
services:
  - docker  
before_install:
  - docker-compose up -d
  - echo "The commit message is" && echo $TRAVIS_COMMIT_MESSAGE
after_script:
  - docker-compose down -d
